# Generated by Django 3.2.18 on 2023-09-23 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Forest_officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=34)),
                ('age', models.CharField(max_length=3)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=6)),
                ('photo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=4)),
                ('place', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=6)),
                ('photo', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=7)),
                ('DIVISION', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.division')),
            ],
        ),
        migrations.CreateModel(
            name='Reservrd_animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ANIMAL', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.animal')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('OFFICER', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.forest_officer')),
            ],
        ),
        migrations.AddField(
            model_name='forest_officer',
            name='LOGIN',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.login'),
        ),
        migrations.AddField(
            model_name='forest_officer',
            name='STATION',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.station'),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(default='', max_length=50)),
                ('date', models.DateField()),
                ('reply', models.CharField(default='pending', max_length=50)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('USER', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='CATEGORY',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.category'),
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=22)),
                ('OFFICER', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.forest_officer')),
                ('STATION', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.station')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('alert', models.CharField(max_length=100)),
                ('OFFICER', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.forest_officer')),
                ('USER', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
