# Generated by Django 3.2.18 on 2023-09-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
