# Generated by Django 3.2.18 on 2023-11-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_animal_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal_notification',
            name='time',
            field=models.TimeField(default='12:00'),
            preserve_default=False,
        ),
    ]
