# Generated by Django 3.2.18 on 2023-11-13 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_animal_notification_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
    ]
