# Generated by Django 3.2.25 on 2025-01-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_complaint_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='status',
        ),
        migrations.AddField(
            model_name='animal',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='animal',
            name='image',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='animal_notification',
            name='detected',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='animal_notification',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
